--------------------------------------------------------
--  File created - Sunday-March-30-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "SAGARIKAMRAJ"."CUSTOMERS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"ADDRESS_LINE1" VARCHAR2(255 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(2 BYTE), 
	"ZIPCODE" NUMBER(5,0), 
	"PHONE" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PSSWORD" VARCHAR2(255 BYTE), 
	"ENROLL_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAGARIKAMRAJ.CUSTOMERS
SET DEFINE OFF;
Insert into SAGARIKAMRAJ.CUSTOMERS (ID,NAME,ADDRESS_LINE1,ADDRESS_LINE2,STATE,ZIPCODE,PHONE,EMAIL,PSSWORD,ENROLL_DATE) values (1,'aaa','2739 Patrick Henry street','apt 000 Chicago','IL',60616,'000-000-0000','1.aaa@gmail.ccom','paswwordtest',to_date('31-JAN-14','DD-MON-RR'));
Insert into SAGARIKAMRAJ.CUSTOMERS (ID,NAME,ADDRESS_LINE1,ADDRESS_LINE2,STATE,ZIPCODE,PHONE,EMAIL,PSSWORD,ENROLL_DATE) values (2,'bbb','street 1','apt 1','IN',11111,'111-111-1111','validemail@yahoo.co.in','validpswd',to_date('20-FEB-13','DD-MON-RR'));
Insert into SAGARIKAMRAJ.CUSTOMERS (ID,NAME,ADDRESS_LINE1,ADDRESS_LINE2,STATE,ZIPCODE,PHONE,EMAIL,PSSWORD,ENROLL_DATE) values (3,'ccc',null,null,null,null,null,null,null,to_date('03-MAR-15','DD-MON-RR'));
Insert into SAGARIKAMRAJ.CUSTOMERS (ID,NAME,ADDRESS_LINE1,ADDRESS_LINE2,STATE,ZIPCODE,PHONE,EMAIL,PSSWORD,ENROLL_DATE) values (4,'ddd',null,null,null,null,null,null,null,null);
Insert into SAGARIKAMRAJ.CUSTOMERS (ID,NAME,ADDRESS_LINE1,ADDRESS_LINE2,STATE,ZIPCODE,PHONE,EMAIL,PSSWORD,ENROLL_DATE) values (5,'eee',null,null,null,null,null,null,null,null);
--------------------------------------------------------
--  DDL for Index CUST_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAGARIKAMRAJ"."CUST_ID" ON "SAGARIKAMRAJ"."CUSTOMERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "SAGARIKAMRAJ"."CUSTOMERS" ADD CONSTRAINT "CUST_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
