--------------------------------------------------------
--  File created - Sunday-March-30-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAGARIKAMRAJ"."ORDER_DETAILS" 
   (	"ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"PRICE" NUMBER, 
	"QUANTITY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAGARIKAMRAJ.ORDER_DETAILS
SET DEFINE OFF;
Insert into SAGARIKAMRAJ.ORDER_DETAILS (ID,ORDER_ID,PRODUCT_ID,PRICE,QUANTITY) values (1,10,1,100,1);
Insert into SAGARIKAMRAJ.ORDER_DETAILS (ID,ORDER_ID,PRODUCT_ID,PRICE,QUANTITY) values (2,20,2,200,22);
Insert into SAGARIKAMRAJ.ORDER_DETAILS (ID,ORDER_ID,PRODUCT_ID,PRICE,QUANTITY) values (3,30,3,300,10);
--------------------------------------------------------
--  DDL for Index ORDER_DETAILS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAGARIKAMRAJ"."ORDER_DETAILS_ID" ON "SAGARIKAMRAJ"."ORDER_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAGARIKAMRAJ"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAGARIKAMRAJ"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_ORDER_ID" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SAGARIKAMRAJ"."ORDERS" ("ID") ENABLE;
 
  ALTER TABLE "SAGARIKAMRAJ"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SAGARIKAMRAJ"."PRODUCTS" ("ID") ENABLE;
