--------------------------------------------------------
--  File created - Sunday-March-30-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SAGARIKAMRAJ"."PRODUCTS" 
   (	"ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"MANUFACTURER_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"MODEL" VARCHAR2(255 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"WEIGHT" NUMBER, 
	"IMAGE_LOCATION" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"COLOR" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAGARIKAMRAJ.PRODUCTS
SET DEFINE OFF;
Insert into SAGARIKAMRAJ.PRODUCTS (ID,CATEGORY_ID,MANUFACTURER_ID,NAME,DESCRIPTION,PRICE,QUANTITY,MODEL,TITLE,WEIGHT,IMAGE_LOCATION,STATUS,COLOR) values (1,1,100,'Product 1','Desc 1',100,1,'X','Prod1',10,'C://','IN STOCK','Red ');
Insert into SAGARIKAMRAJ.PRODUCTS (ID,CATEGORY_ID,MANUFACTURER_ID,NAME,DESCRIPTION,PRICE,QUANTITY,MODEL,TITLE,WEIGHT,IMAGE_LOCATION,STATUS,COLOR) values (2,2,200,'Product 2','DDesc 2',200,2,'Y','PProd2',20,'D://','NO STOCK','Black');
Insert into SAGARIKAMRAJ.PRODUCTS (ID,CATEGORY_ID,MANUFACTURER_ID,NAME,DESCRIPTION,PRICE,QUANTITY,MODEL,TITLE,WEIGHT,IMAGE_LOCATION,STATUS,COLOR) values (3,3,300,'Product 3','Desc 3',300,3,'Z','Prod3',30,'E://','NO STOCK','BBrown');
--------------------------------------------------------
--  DDL for Index PRODUCT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAGARIKAMRAJ"."PRODUCT_ID" ON "SAGARIKAMRAJ"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SAGARIKAMRAJ"."PRODUCTS" ADD CONSTRAINT "PRODUCT_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SAGARIKAMRAJ"."PRODUCTS" ADD CONSTRAINT "PRODUCT_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "SAGARIKAMRAJ"."CATEGORIES" ("ID") ENABLE;
 
  ALTER TABLE "SAGARIKAMRAJ"."PRODUCTS" ADD CONSTRAINT "PRODUCT_MANUFACTURER_ID" FOREIGN KEY ("MANUFACTURER_ID")
	  REFERENCES "SAGARIKAMRAJ"."MAUFACTURERS" ("ID") ENABLE;
